name: Build and Release Alfred Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'info.plist'
      - 'src/**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up workflow variables
        id: vars
        run: |
          workflow_name=$(grep -A1 '<key>name</key>' info.plist | tail -n1 | sed -e 's/<[^>]*>//g' | awk '{$1=$1;print}' | tr -d '\r')
          echo "workflow_name=$workflow_name" >> $GITHUB_OUTPUT
          version=$(grep -A1 '<key>version</key>' info.plist | tail -n1 | sed -e 's/<[^>]*>//g' | tr -d '[:space:]')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check version increment
        run: bash ./dev/check-version-increment.sh

      - name: Create .alfredworkflow file
        run: |
          zip -r "${{ steps.vars.outputs.workflow_name }}.alfredworkflow" info.plist -x prefs.plist

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.vars.outputs.version }}
          name: Release v${{ steps.vars.outputs.version }}
          draft: false
          prerelease: false
          files: "${{ steps.vars.outputs.workflow_name }}.alfredworkflow"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
